# lathe — hands-on technical tutorials generated by, and worked through outside of, an
# agent session.
#
# Not in nixpkgs (checked at the locked revision), and upstream ships a Homebrew *cask*
# for macOS plus a `curl | sh` script for Linux. Neither is usable here: the cask is
# macOS-only, and this repo's rule is that a tool present on more than one host is built
# from the same locked source on all of them. It is plain Go with CGO off and no asset
# pipeline (see upstream .goreleaser.yaml), so buildGoModule reproduces the release
# binary exactly, including the version stamp the UI shows.
#
# The skills are embedded in the binary and written out by `lathe skills install`, whose
# targets are agent-specific directories — there is no OMP target. So the build asks the
# binary for its own skills and stages them under share/, and hm-modules/omp.nix links
# each one into ~/.omp/agent/skills/<name>/. Running the binary rather than copying
# .claude/skills/ out of the source tree keeps this correct if upstream changes where the
# embedded copies live.
{
  buildGoModule,
  fetchFromGitHub,
  lib,
}:

buildGoModule (finalAttrs: {
  pname = "lathe";
  # renovate: datasource=github-releases depName=devenjarvis/lathe
  version = "0.5.0";

  src = fetchFromGitHub {
    owner = "devenjarvis";
    repo = "lathe";
    tag = "v${finalAttrs.version}";
    hash = "sha256-3QkHfIM21MeEPl4EnDw3SUU5f/hoHu2MieapqWX2Aqs=";
  };

  vendorHash = "sha256-3QV/ocKpCu2cmefLBCf4ZAAgFbN3500To5qpMinm+uM=";

  env.CGO_ENABLED = 0;

  # Same stamps the release workflow sets. Without Version the UI and `lathe version`
  # report "dev", and the update check compares against a version that never matches.
  ldflags = [
    "-s"
    "-w"
    "-X github.com/devenjarvis/lathe/internal/buildinfo.Version=${finalAttrs.version}"
    "-X github.com/devenjarvis/lathe/internal/buildinfo.Commit=v${finalAttrs.version}"
    "-X github.com/devenjarvis/lathe/internal/buildinfo.Date=1970-01-01T00:00:00Z"
  ];

  # The skill set is enumerated here rather than globbed at use time, because
  # home-manager needs the names at evaluation time and reading them out of the store
  # would mean import-from-derivation. postInstall fails the build if this list and the
  # binary disagree, so a version bump that adds or renames a skill cannot land silently.
  passthru.skillNames = [
    "lathe"
    "lathe-ask"
    "lathe-extend"
    "lathe-tag"
    "lathe-verify"
    "lathe-voice"
    "lathe-work"
  ];

  postInstall = ''
    stage=$(mktemp -d)
    # `skills install` without --user writes into ./.claude/skills, and the source tree
    # already contains one of those, so run it somewhere empty.
    ( cd "$stage" && HOME="$stage" "$out/bin/lathe" skills install --agent claude-code >/dev/null )
    installed=$(cd "$stage/.claude/skills" && echo *)
    declared="${lib.concatStringsSep " " finalAttrs.passthru.skillNames}"
    if [ "$installed" != "$declared" ]; then
      echo "lathe skills changed upstream:" >&2
      echo "  binary ships: $installed" >&2
      echo "  packages/lathe.nix declares: $declared" >&2
      echo "Update passthru.skillNames (hm-modules/omp.nix links each name)." >&2
      exit 1
    fi
    mkdir -p "$out/share/lathe"
    cp -r "$stage/.claude/skills" "$out/share/lathe/skills"
  '';

  meta = {
    description = "Generate, store, serve, verify, and extend hands-on technical tutorials";
    homepage = "https://github.com/devenjarvis/lathe";
    license = lib.licenses.mit;
    mainProgram = "lathe";
    platforms = lib.platforms.darwin ++ lib.platforms.linux;
  };
})
